# Colamanga 破甲模块 - hook 开关配置（WebUI 实时改，so 每 256 次调用重读，无需重启）
# 1=启用 0=禁用
hook_property=1
hook_property_cb=1
hook_ptrace=1
hook_access=1
hook_open=1
hook_openat=1
hook_stat=1
hook_uname=1
hook_connect=1
hook_getaddrinfo=1
hook_jni=1
hook_read=1
hook_ssl_unlock=1
file_sandbox=1
hide_maps=1
net_blocklist=1
